# Changes here will be overwritten by Copier.
_commit: 0.7.0
_src_path: https://github.com/mgaitan/python-package-copier-template
author_email: gaitan@gmail.com
author_fullname: Martín Gaitán
author_username: mgaitan
copyright_license: BSD-3-Clause
gh_repo_create: skip
project_description: A Tetris game for your terminal, built with the Textual framework.
project_name: Textual Tetris
python_package_command_line_name: textual-tetris
python_package_distribution_name: textual-tetris
python_package_import_name: textris
repository_name: textual-tetris
